[package]
name = "accelerate-txs-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = "0.32"
bdk_wallet = "1.0"
bitcoincore-rpc = "0.19"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
hex = "0.4"
